/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vramachandran' at '2/8/16 10:24 PM' with Gradle 2.2.1
 *
 * @author vramachandran, @date 2/8/16 10:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
